version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-collaboration-engine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collaboration-engine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postresql/data

  redis:
    image: redis:7
    container_name: redis-collaboration-engine
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
